name: rohanbatra
description: A Flutter package for Rohan Batra's personal website, showcasing his portfolio, projects, and achievements.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0-70.0.dev

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  lottie: ^3.3.1
  shared_preferences: ^2.5.3
  flutter_animate: ^4.2.0
  font_awesome_flutter: ^10.7.0 # Check for latest version
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon_navbar-light-bg.png
    - assets/icons/icon_navbar-dark-bg.png
    - assets/icons/icon_back-arrow-dark-bg.png
    - assets/icons/icon_back-arrow-light-bg.png
    - assets/animations/loading.json
    - assets/animations/education.json
    - assets/animations/panda.json
    - assets/animations/writer.json
    - assets/animations/developer.json
    - assets/animations/research.json
    - assets/animations/about_me.json
    - assets/logos/Rohan-Batra/bg-logo.png
    - assets/logos/Rohan-Batra/legacy-logo.png
    - assets/logos/Rohan-Batra/logo.png
    - assets/logos/Kruxers/Dark-Mode/logo.png
    - assets/logos/Kruxers/Light-Mode/logo.png
    - assets/logos/Linuxwale/Dark-Mode/logo.png
    - assets/logos/Linuxwale/Light-Mode/logo.png
    - assets/logos/Rohan-Batra-Gaming/Dark-Mode/logo.png
    - assets/logos/Rohan-Batra-Gaming/Light-Mode/logo.png
    - assets/logos/Rohan-Batra-FOSS/Dark-Mode/logo.png
    - assets/logos/Rohan-Batra-FOSS/Dark-Mode/logo2.png
    - assets/logos/Rohan-Batra-FOSS/Dark-Mode/logo3.png
    - assets/logos/Rohan-Batra-FOSS/Light-Mode/logo.png
    - assets/logos/Rohan-Batra-FOSS/Light-Mode/logo2.png
    - assets/logos/Rohan-Batra-FOSS/Light-Mode/logo3.png
    - assets/logos/Second-Brain-Database/Dark-Mode/logo.png
    - assets/logos/Second-Brain-Database/Light-Mode/logo.png
    - assets/logos/Ravage-Gamer/Mascots/Mascot.png
    - assets/logos/UPES/UPES1.png
    - assets/logos/UPES/UPES2.png
    - assets/logos/SMCS/building.jpg
    - assets/animations/professional.json
    - assets/animations/source-code.json
    - assets/animations/experience.json
    - assets/animations/non-profit.json
    - assets/animations/portfolio.json
    - assets/animations/download.json
    - assets/animations/contactus.json
    - assets/images/certificates/certificate1.jpg
    - assets/images/certificates/certificate2.jpg
    - assets/images/certificates/certificate3.jpg
    - assets/images/certificates/certificate4.jpg
    - assets/images/certificates/certificate5.jpg
    - assets/images/certificates/certificate6.jpg
    - assets/images/certificates/certificate7.jpg
    - assets/logos/IITB/ECELL/ecell_iitb_logo.jpg
    - assets/logos/Science-Olympiad-Foundation/logo.jpg
    - assets/logos/Pentasoft/pentelogo.png
    - assets/logos/UNSW/unsw-logo.png
    - assets/logos/TERI/teriin_logo.jpg
    - assets/logos/Orange-Education/orangeeducation_logo.jpg
    - assets/images/certificates/E-CELL/Eureka-2021-22.png
    - assets/images/certificates/E-CELL/Eureka-2022-23.png
    - assets/images/certificates/E-CELL/workshop.jpg
    - assets/images/certificates/SOF/certificate-nco-3.jpg
    - assets/images/certificates/SOF/certificate-nco-4.jpg
    - assets/images/certificates/SOF/certificate-nco-5.jpg
    - assets/images/certificates/SOF/certificate-imo-4.jpg
    - assets/images/certificates/SOF/certificate-imo-5.jpg
    - assets/images/certificates/SOF/certificate-imo-6.jpg
    - assets/images/certificates/SOF/certificate-imo-7.jpg
    - assets/images/certificates/SOF/certificate-nso-5.jpg
    - assets/images/certificates/SOF/certificate-nso-6.jpg
    - assets/images/certificates/SOF/certificate-nso-7.jpg    
    - assets/images/certificates/Pentasoft/certificate2.jpg
    - assets/images/certificates/Pentasoft/certificate1.jpg
    - assets/images/certificates/UNSW/certificate2.jpg
    - assets/images/certificates/UNSW/certificate1.jpg
    - assets/images/certificates/TERI/certificate1.jpg
    - assets/images/certificates/NAO/certificate1.jpg
    - assets/images/certificates/UPES/certificate1.jpg
    - assets/images/banners/branding-kit.jpg
    - assets/images/banners/Emotion-Tracker/Light-Mode/banner.png
    - assets/images/banners/Emotion-Tracker/Dark-Mode/banner.png
    - assets/images/banners/Knowledge-Base/Dark-Mode/2.png
    - assets/images/banners/Knowledge-Base/Light-Mode/1.png
    - assets/images/banners/Second-Brain-2022/2.png
    - assets/images/banners/Second-Brain-2022/1.png
    - assets/images/banners/Configs/1.png
    - assets/images/banners/Configs/2.png
    - assets/images/banners/Landing-Pages/Light-Mode/banner.png
    - assets/images/banners/Landing-Pages/Dark-Mode/banner.png
    - assets/images/banners/Portfolio/Dark-Mode/2.png
    - assets/images/banners/Portfolio/Light-Mode/1.png
    - assets/images/banners/SBDFS/Light-Mode/1.png
    - assets/images/banners/SBDFS/Dark-Mode/2.png
    - assets/images/banners/SBD-Flutter-Template/Light-Mode/1.png
    - assets/images/banners/SBD-Flutter-Template/Dark-Mode/2.png
    - assets/images/banners/Scripts/Light-Mode/1.png
    - assets/images/banners/Scripts/Dark-Mode/2.png
    - assets/images/banners/Second-Brain-Tools-2022/Light-Mode/1.png
    - assets/images/banners/Second-Brain-Tools-2022/Dark-Mode/2.png
    - assets/images/banners/Second-Brain-Database/Dark-Mode/banner.png
    - assets/images/banners/Second-Brain-Database/Light-Mode/banner.png
    - assets/images/banners/Suckless-St/Light-Mode/2.png
    - assets/images/banners/Suckless-St/Dark-Mode/1.png
    - assets/images/banners/Dmenu/Light-Mode/1.png
    - assets/images/banners/Dmenu/Dark-Mode/2.png
    - assets/images/banners/Dwm/Light-Mode/1.png
    - assets/images/banners/Dwm/Dark-Mode/2.png
    - assets/images/banners/Second-Brain-Database-Flutter-Frontend/Dark-Mode/2.png
    - assets/images/banners/Second-Brain-Database-Flutter-Frontend/Light-Mode/1.png
    - assets/images/banners/Second-Brain-Database-Telegram-Bot/Light-Mode/1.png
    - assets/images/banners/Second-Brain-Database-Telegram-Bot/Dark-Mode/2.png
    - assets/images/certificates/Caring-Souls/1.jpg
    - assets/images/certificates/UBSA/1.jpg
    - assets/logos/Indian-Armed-Forces/logo.png
    - assets/images/certificates/IAF/1.jpg
    - assets/images/certificates/IAF/2.jpg
    - assets/images/certificates/IAF/3.jpg
    - assets/logos/Proxmox/whitemode-logo.png
    - assets/logos/Proxmox/darkmode-logo.png
    - assets/images/banners/Proxmox/darkmode-banner.png
    - assets/images/banners/Proxmox/lightmode-banner.png
    - assets/logos/THM/THMlogo-gray_scale.png
    - assets/logos/THM/Tryhackme-light.png
    - assets/images/banners/THM/1.png
    - assets/images/banners/THM/2.png
    - assets/images/banners/Garuda-Linux/1.png
    - assets/images/banners/Garuda-Linux/2.png
    - assets/images/banners/Kali-Linux/1.png
    - assets/images/banners/Kali-Linux/2.png
    - assets/images/banners/Debian-Linux/1.png
    - assets/images/banners/Debian-Linux/2.png
    - assets/images/banners/Arch-Linux/1.png
    - assets/images/banners/Arch-Linux/2.png
    - assets/images/banners/Proxmox/1.png
    - assets/images/banners/Proxmox/2.png
    - assets/images/banners/Cachy-OS/1.png
    - assets/images/banners/Cachy-OS/2.png
    - assets/images/banners/Arch-Linux-and-Manjaro/1.png
    - assets/images/banners/Arch-Linux-and-Manjaro/2.png
    - assets/images/banners/Ansible/1.png
    - assets/images/banners/Ansible/2.png
    - assets/images/banners/Github-Actions/1.png
    - assets/images/banners/Github-Actions/2.png
    - assets/images/banners/N8N/2.png
    - assets/images/banners/N8N/1.png
    - assets/images/banners/make/1.png
    - assets/images/banners/make/2.png
    - assets/images/banners/Zapier/1.png
    - assets/images/banners/Zapier/2.png
    - assets/images/banners/ifttt/2.png
    - assets/images/banners/ifttt/1.png
    - assets/images/banners/Selenium/1.png
    - assets/images/banners/Selenium/2.png
    - assets/images/banners/ANDROID/1.png
    - assets/images/banners/ANDROID/2.png
    - assets/images/banners/FASTBOOT/2.png
    - assets/images/banners/FASTBOOT/1.png
    - assets/images/banners/Magisk/2.png
    - assets/images/banners/Magisk/1.png
    - assets/images/banners/MSM/1.png
    - assets/images/banners/MSM/2.png
    - assets/images/banners/Samsung-Odin/1.png
    - assets/images/banners/Samsung-Odin/2.png
    - assets/images/banners/TWRP/2.png
    - assets/images/banners/TWRP/1.png
    - assets/images/banners/supersu/2.png
    - assets/images/banners/supersu/1.png
    - assets/images/banners/SP-FLASH-TOOL/1.png
    - assets/images/banners/SP-FLASH-TOOL/2.png
    - assets/images/banners/OrangeFox/1.png
    - assets/images/banners/OrangeFox/2.png
    - assets/images/banners/MTKCLIENT/1.png
    - assets/images/banners/MTKCLIENT/2.png
    - assets/images/banners/Asana/1.png
    - assets/images/banners/Asana/2.png
    - assets/images/banners/Clickup/1.png
    - assets/images/banners/Clickup/2.png
    - assets/images/banners/Monday/1.png
    - assets/images/banners/Monday/2.png
    - assets/images/banners/Trello/1.png
    - assets/images/banners/Trello/2.png
    - assets/images/banners/Alto-Adventure/1.png
    - assets/images/banners/Alto-Adventure/2.png
    - assets/images/banners/BGMI/1.png
    - assets/images/banners/BGMI/2.png
    - assets/images/banners/Call-of-duty/1.png
    - assets/images/banners/Call-of-duty/2.png
    - assets/images/banners/minecraft/1.png
    - assets/images/banners/minecraft/2.png
    - assets/images/banners/Godot/1.png
    - assets/images/banners/Godot/2.png
    - assets/images/banners/Renpy/1.png
    - assets/images/banners/Renpy/2.png
    - assets/images/banners/Unity/1.png
    - assets/images/banners/Unity/2.png
    - assets/images/banners/UnrealEngine/1.png
    - assets/images/banners/UnrealEngine/2.png
    - assets/images/banners/clockify/2.png
    - assets/images/banners/clockify/1.png
    - assets/images/banners/Anno-1800/2.png
    - assets/images/banners/Anno-1800/1.png
    - assets/images/banners/obsidian/2.png
    - assets/images/banners/obsidian/1.png
    - assets/images/banners/marklang/1.png
    - assets/images/banners/marklang/2.png
    - assets/images/banners/proxmox-auto-install-assistant-docker/1.png
    - assets/images/banners/proxmox-auto-install-assistant-docker/2.png
    - assets/images/banners/karmstrot-builds/1.png
    - assets/images/banners/karmstrot-builds/2.png
    - assets/images/banners/blog/1.png
    - assets/images/banners/blog/2.png
    - assets/animations/iNi4lrRvEq.json
    - assets/animations/IceAcvKhR4.json
    - assets/animations/5b6C8UQeUj.json
    - assets/animations/GGN8CoO0KB.json
    - assets/animations/pUBqZ5WbTy.json
    - assets/animations/gBuOxKdbdC.json

# flutter_launcher_icons:
#   android: "launcher_icon"
#   image_path: "assets/logo.png"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/logo.png"
#     background_color: "#FFFFFF" # Change to your preferred color
#     theme_color: "#000000" # Change to your preferred color
#   windows:
#     generate: true
#     image_path: "assets/logo.png"
#     icon_size: 256 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/logo.png"


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
